import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

import LandingNavbar from "@/components/layouts/landing/landing-navbar";
import Footer from "@/components/layouts/landing/footer";
import { ThemeProvider } from "./NextThemeProvider";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ThemeProvider
					enableSystem
					disableTransitionOnChange
					attribute="class"
					defaultTheme="system"
				>
					{/* <Auth /> */}
					<div className="container">
						<LandingNavbar />
					</div>
					{children}
					<Footer />
				</ThemeProvider>
			</body>
		</html>
	);
}
