import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

import Footer from "@/components/layouts/landing/footer";
import { ThemeProvider } from "./NextThemeProvider";
import { Header } from "@/components/layouts/landing/header";
import { Toaster } from "@/components/ui/toaster";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

// export const preload = () => {
// 	// TODO: cached Auth?
// };

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col`}
			>
				<ThemeProvider
					enableSystem
					disableTransitionOnChange
					attribute="class"
					defaultTheme="system"
				>
					{/* <Auth /> */}
					<Header />
					<div className="flex-grow flex">{children}</div>
					<Footer />
					<Toaster />
				</ThemeProvider>
			</body>
		</html>
	);
}
